# Please refer https://aka.ms/HTTPSinContainer on how to setup an https developer certificate for your ASP .NET Core service.

version: '3.4'

services:
  truedevice:
    image: munya250/truedevice
    build:
      context: ./TrueDevice/Api
      dockerfile: Dockerfile
    ports:
      - "80:80"
    depends_on: 
     - sqlserver
     
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2019-latest
    environment:
       USER: "sa"
       ACCEPT_EULA: "Y"
       SA_PASSWORD: "Pa55w0rd2021"
       MSSQL_PID: Express
    ports: 
     - "1433:1433"
